### ISSUE TITLE
Don't use hard coded iteration count in PBKDF2

### ISSUE THREAD

**Issue by totalvoidness** [Sirrix-AG/PanBox#1]
These specs are far to easy to bruteforce. This is just the level of security used in WPA2.

	SecretKeyFactory f = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA1");
	KeySpec ks = new PBEKeySpec(userpass, salt, 4096, 512);

4096 iterations of sha1 aren't exactly state of the art. (One could believe a certain ministry has an interest in being able to crack the keystore when confiscating PCs...)

You should consider using a dynamic iteration count which gets adjusted during the next few years.

**Comment by caschulz88** [comment]
Hey, thanks for the feedback. We will have a look at that and will act on it!

**Comment by caschulz88** [comment]
Hey, thanks for the reply. But also this is dead code which has not been removed yet. We will remove it from Git soon. Thanks!

**Comment by totalvoidness** [comment]
Ok thanks. Where is the actual encryption happening then?

**Comment by caschulz88** [comment]
If you are searching for the real file encryption: This is implemented in the org.panbox.core.crypto.io package. The encryption of file names (obfuscation) is implemented in the org.panbox.core.crypto package (mainly Obfuscator).

Please also check the tests for encryption and obfuscation to see the actual usage.

**Comment by totalvoidness** [comment]
Thank you :+1:

**Comment by rw-p** [comment]
To be a little bit more specific: For encryption of file contents, Panbox uses the AES GCM based implementations within org.panbox.core.crypto.io, following a chunk based approach. Obfuscation is done via org.panbox.core.crypto.Obfuscator. IV storage and processing (for filename obfuscation) is handled via subclasses of org.panbox.core.crypto.AbstractObfuscatorIVPool. Key-Pairs are currently stored within standard Bouncycastle-Keystores..

**Comment by totalvoidness** [comment]
Thanks for the update. That sounds a lot more like what I'd expect from the Fraunhofer SIT. Whatever you were doing with the ECB code before was kind of shocking ;) But as you're about to remove it now, I'm relieved

**Comment by caschulz88** [comment]
FYI: The dead code has been removed.
