### ISSUE TITLE
Fehlende Lib: jniopencv_highgui (Debian 7 Wheezy Stable)

### ISSUE THREAD

**Issue by SebStaeubert** [Sirrix-AG/PanBox#11]
Liebes Panbox-Team,

folgender Fehler kommt unter Linux, wenn man nach Aufruf von start.sh auf den Button "Gerät koppeln" klickt:

#####
java.lang.UnsatisfiedLinkError: no jniopencv_highgui in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:524)
	at org.bytedeco.javacpp.Loader.load(Loader.java:399)
	at org.bytedeco.javacpp.Loader.load(Loader.java:353)
	at org.bytedeco.javacpp.opencv_highgui.<clinit>(opencv_highgui.java:13)
	at org.bytedeco.javacv.OpenCVFrameGrabber.start(OpenCVFrameGrabber.java:174)
	at org.panbox.desktop.common.pairing.cam.OpenCVWebCam.start(Unknown Source)
	at org.panbox.desktop.common.pairing.cam.Utils.listVideoDevices(Unknown Source)
	at org.panbox.desktop.common.gui.PairThisDeviceDialog.loadDeviceList(Unknown Source)
	at org.panbox.desktop.common.gui.PairThisDeviceDialog.<init>(Unknown Source)
	at org.panbox.desktop.common.PanboxClient.initIdentity(Unknown Source)
	at org.panbox.desktop.common.PanboxClient.<init>(Unknown Source)
	at org.panbox.desktop.linux.PanboxClient.<init>(Unknown Source)
	at org.panbox.desktop.linux.PanboxClient.main(Unknown Source)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/javacpp52806430734593/libjniopencv_highgui.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/javacpp52806430734593/libjniopencv_highgui.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1062)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:513)
	... 12 more
#####

OS: Debian 7
Alle Libs, die in der readme.txt gefordert sind, wurden installiert. Welche Lib fehlt?

Gruß,
Seb.

P.S.: Die Software ist entgegen der Pressemeldungen meilenweit davon entfernt benutzerfreundlich und massentauglich zu sein!!! Ich bin sehr enttäuscht! Zu viele Fehler, zu kompliziert bzw. unintuitiv. Dabei meine ich nicht einmal den jetzt beschriebenen Fehler. Weitere Beispiele:
1. Kopplung von Geräten (möglich, aber zu fehleranfällig und zu kompliziert):
  - per QR-Code aussichtslos - der Code wird nicht erkannt
  - manuell: Abtippen eines ellenlangen Codes in kurzer Zeit auf einer fummeligen Handy/Tablet-Tastatur?!
  - Windows-Client (Master) hat seinen Server zur Kopplung nat. nur auf localhost laufen, was man nur im Expertenmodus sieht und ändern kann...
2. Shares (habe ich bisher nicht geschafft zu nutzen!):
  - Angelegt, freigegeben auch im Windows-Explorer zu sehen aber nicht schreibbar?!
  - Panbox-Ordner unter Dropbox/Panbox angelegt: darin ein Share angelegt - ist nicht auf dem Tablet zu sehen

Da ist noch einiges zu tun und ich hoffe auf eine neue Version!

**Comment by SebStaeubert** [comment]
Ok, eine Recherche lieferte, dass in Debian 7 die libc6 in Version 2.13 installiert ist, Panbox aber Version 2.14 benötigt.

Wird es eine Debian-kompatible Version von Panbox geben, d.h. gegen libc6 2.13 gelinkt?

Workaround wie dieser hier http://unix.stackexchange.com/questions/85505/need-to-install-glibc-2-14-on-wheezy funktionieren leider nicht.

Danke und Gruß,
Seb.

**Comment by caschulz88** [comment]
Hallo Seb,

vielen Dank für dein Feedback. Wir haben bereits viel an PanBox in den letzten 2 Wochen getan und planen gerade einen Release der Version 1.1 möglichst bald durchzuführen. Darin sind auch einige Fixes die die Benutzerfreundlichkeit verbessern werden.

Zu diesem konkreten Fall kann ich sagen, dass wir die JavaCV Bibliotheken in der Version 0.09 mitliefern, die wiederum OpenCV in der Version 2.4.9 beinhaltet. Diese Bibliotheken stammen von JavaCV selbst. Die Bibliothek kann aber lokal gegen eine ältere oder neuere Version ausgetauscht werden, falls Debitan 7 stable hier Probleme machen sollte. Mittlerweile ist die Version 0.10 aktuell, wobei diese wahrscheinlich eine noch neuere libc Version voraussetzen könnte. Sie könnten die Version 0.08 bei Ihnen lokal ausprobieren:

https://repo1.maven.org/maven2/org/bytedeco/javacv/0.8/

Da dieses Problem bisher nicht aufgetreten ist müssen wir zunächst untersuchen ob ein Wechsel auf die Version 0.08 dazu ggf. führen würde, dass Distributionen, die bisher getestet wurden und auf denen es keine Probleme gab, dann problematisch werden könnten (beispielsweise Ubuntu 14.04, Fedora 20/21, etc.)

Zu den anderen Dingen, die Sie erwähnten:
- Das QR-Codescanning dauert derzeit noch sehr lange (ca. 5-10 Sekunden, abhängig vom Gerät). Das ist zu lange und wir arbeiten an einer Lösung. Ob diese bereits in der Androidversion 1.1 Teil sein wird kann ich aber derzeit nicht sagen.
- Das Problem mit dem standardmäßigen Lauschen auf der localhost-IP-Adresse ist bereits gefixt und wird in der Version 1.1 veröffentlicht.
- Zu dem Problem mit den nicht-schreibbaren Shares möchte ich Sie bitten einen neuen Issue anzulegen und dort die Service und Client logs anzuhängen. Das Client log (PanboxWindowsClient.log) liegt in Windows unter dem Pfad "%APPDATA%\Panbox.org\Panbox" und das Service log (PanboxWindowsService.log) unter "C:\Windows\System32" bzw. "C:\Windows\SysWow64".
- Die Android-App unterstützt grundsätzlich derzeit nur Shares, die direkt im Wurzelverzeichnis des Dropbox-Ordners angelegt werden. Legen Sie den Share also nicht in den Unterordner Panbox sondern direkt in das Wurzelverzeichnis, wird dieser auch von der Android-App erkennt. Auf Grund der viel geringeren Bandbreite und Rechenkraft auf mobilen Geräten ist es leider nicht möglich zunächst gesamte Verzeichnisstrukturen nach PanBox Shares zu durchsuchen und diese dann auch in Teilen von Unterordnern anzeigen zu lassen. Eine Funktion zum manuellen Hinzufügen von PanBox Shares aus manuell gewählten Unterverzeichnissen ließe sich aber sicherlich in der Zukunft realisieren und haben wir bereits als Wunsch notiert.

Wir nehmen jeden Punkt sehr ernst und entwickeln PanBox stetig in alle Richtungen weiter. Auch wenn in der Version 1.1 nicht all Ihre Wünschen realisiert und die aufgetretenen Probleme gefixt sein sollten, so werden diese in kommenden Versionen umgesetzt.

Vielen Dank!

PS: Gerne können Sie uns Rückmeldung in diesem Issue geben, falls Sie Erfolg mit der Verwendung von JavaCV in Version 0.08 hatten.

**Comment by SebStaeubert** [comment]
@caschulz88 Danke für die Antworten.

javacv v0.8 scheint die aktuell mit Panbox ausgelieferte Version zu sein - jedenfalls ist die Version 0.8 aus dem obigen Link identisch mit der im lib-Verzeichnis der Linux-Version. Dementsprechend ändern sich die Fehlermeldungen auch nicht.

Es gibt im Debian ähnliche Pakete:
* python-opencv
* libopencv-*2.3
Ich habe testweise mal alle installiert - ändert leider nichts an der Fehlermeldung.

Wozu wird opencv überhaupt gebraucht? Für die Kopplung des Linux-Clients wird doch keine Kameraansteuerung (dafür ist doch opencv/javacv gedacht, oder?) benötigt - hierzu habe ich eine Zip-Datei vom Master-Client (in der Windows-Version auf einem anderen PC) erzeugt. Evtl. macht es Sinn diese Libs nur zu laden, wenn die grafische Kopplung gewählt wird (was am Linux-Client vermutlich nicht so häufig vorkommt?!).

Zu den anderen Punkten:
* QR: Ok.
* Pairing / Localhost: Ok, prima.
* readonly-Shares: Ok, mache ich bei Gelegenheit.
* Shares in Unterordnern: Ok, danke für den Hinweis.

**Comment by caschulz88** [comment]
Hallo,

ich habe gerade eben die Version 0.08 gecheckt - diese verwendet auch bereits OpenCV 2.4.9, weshalb das Problem identisch ist. Das nachinstallieren der Abhängigkeiten durch Ihren Paketmanager bringt leider keine Veränderung, da die nativen Bibliotheken von OpenCV Teil des jar-Archivs "opencv-linux-x86.jar" bzw. "opencv-linux-x86_64.jar" ist und diese automatisch durch Java geladen werden.

Ich werde mal probieren eine Lösung für dieses Problem zu finden - eventuell gibt es eine compat-library für libc, die auch die Nutzung von 2.14 Code ermöglicht.

OpenCV wird im Desktop-Client für das Ansprechen der Kamera genutzt, um einen QR-Code scannen zu können. Identisch zum Android-Smartphone ist es damit auch möglich auf beispielsweise Windows oder Linux Tablets ein Pairing per Scannen des QR-Codes durchzuführen. Die Erkennung dauert hier übrigens nur einen Bruchteil der Zeit, die die Android App derzeit noch benötigt.

Die Library wird grundsätzlich bei Java nur dann geladen, wenn Sie benötigt wird. Bei dem Klick auf "Gerät koppeln" wird bereits ein Kamera-Liveview angezeigt, wie es auch von der Android-App gemacht wird. Daher wird dann auch schon die Library geladen. Es könnte jedoch ein Extra-Check eingebaut werden, falls das Laden der Bibliothek nicht funktionieren sollte, dass dann immer noch das Dialog ohne LiveView und QR-Scanner funktionstüchtig sei. Eine geeignete Implementierung ist bereits umgesetzt für den Fall, dass gar keine Webcam gefunden werden kann.

Vielen Dank für die Anregung. Ich schließe das nun hier und nehme das Geräte-Koppeln-Dialog auch ohne funktionierende OpenCV-Library als Feature-Request auf.
