### ISSUE TITLE
Do not use ECB mode

### ISSUE THREAD

**Issue by totalvoidness** [Sirrix-AG/PanBox#3]
Please tell me, that you're not using ECB mode!

	aesCipher = Cipher.getInstance(KeyConstants.SYMMETRIC_ALGORITHM);

KeyConstants.SYMMETRIC_ALGORITHM resolves to `"AES"`, which by default is [AES/ECB/PKCS5Padding](http://stackoverflow.com/questions/6258047/java-default-crypto-aes-behavior).

If this is true, you must recall version 1.0 now

**Comment by totalvoidness** [comment]
Update: Just checked for BouncyCastle explicitly: http://stackoverflow.com/questions/4746303/bouncy-castle-default-modes-aes-256

This confirms the usage of [ECB](http://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Electronic_Codebook_.28ECB.29).

**Comment by caschulz88** [comment]
Hey, thanks for the post, but the mentioned code is just dead and not called by any implementation of PanBox :) We will remove this code in Git in the next days.

**Comment by totalvoidness** [comment]
Good to know. Kind of paniced when I saw that! :D
