### ISSUE TITLE
E-Mail regex too restrictive

### ISSUE THREAD

**Issue by sosswald** [Sirrix-AG/PanBox#7]
The `EMAIL_PATTERN` in `org.panbox.desktop.common.gui.SetupWizardDialog` is too restrictive as it does not allow hyphens in domain names (except for the first subdomain after the at sign), effectively locking out users from domains like uni-bonn.de.

**Comment by caschulz88** [comment]
Hi, thanks for the issue. We already noticed some issues with your restricted regex also for other domains. We will include a less restrictive regex soon. It will also be included to the PanBox 1.1 release version which is coming soon.

**Comment by caschulz88** [comment]
Good new for you!

I just replaced the restricted email address regex with the RFC 2822 regex for email address verification.

Please check also this commit:

https://github.com/Sirrix-AG/PanBox/commit/093db5a1a2937b7fb7b9d6e333bf52e91adf740c

Please open a new issue in case you find some other problem.
