### ISSUE TITLE
Right-clicking buttons breaks the GUI

### ISSUE THREAD

**Issue by Nicewuerfel** [Sirrix-AG/PanBox#75]
This issue seems kind of random, but right-clicking multiple buttons in the UI seems to break the whole app. Only a complete restart of the program breaks it.

I'm using PanBox 1.1.2 on Windows 10.

Here is a video of the bug: https://youtu.be/fIIDMOc4QXE

**Comment by caschulz88** [comment]
Hi, thanks for opening an issue. Can you please also attach some more detailed system information? I tried to reproduce this issue on my Windows 10 system with PanBox 1.1.2 and could reproduce this issue for now. Perhaps this is related to some Java issue in the GUI together with some special hardware like graphic adapter or GPU drive, etc. I would like to understand what is the actual issue there and perhaps we can adjust PanBox client GUI to have some work around for exactly this issue.

**Comment by Nicewuerfel** [comment]
I updated my Oracle JDK (64-bit) 8u72 to 8u74 and the issue seems to be gone.
